### ISSUE TITLE
Cell约束冲突

### ISSUE THREAD

**Issue by BetrayalPromise** [depaba/UIView-DPCollapsibleConstraints#1]
作者你好 我在使用的时候发现有约束冲突
2017-04-06 09:54:54.430988+0800 Demo[42206:1126591] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<MASLayoutConstraint:0x6080000ba7c0 UILabel:0x7f816bc1ae00.top == UITableViewCellContentView:0x7f816bc818c0.top + 8>",
    "<MASLayoutConstraint:0x6080000bbc60 UILabel:0x7f816bc7d9d0.top == UILabel:0x7f816bc1ae00.bottom>",
    "<MASLayoutConstraint:0x6080000bb660 UIView:0x7f816bc66320.top == UILabel:0x7f816bc7d9d0.bottom + 10>",
    "<MASLayoutConstraint:0x6080000ba9a0 UIView:0x7f816bc66320.height == 36>",
    "<MASLayoutConstraint:0x6080000bb3c0 UIImageView:0x7f816bc7c4d0.top == UIView:0x7f816bc66320.bottom>",
    "<MASLayoutConstraint:0x6080000bab80 UIImageView:0x7f816bc7c4d0.bottom == UITableViewCellContentView:0x7f816bc818c0.bottom>",
    "<NSLayoutConstraint:0x600000095720 UITableViewCellContentView:0x7f816bc818c0.height == 25>"
)

Will attempt to recover by breaking constraint 
<MASLayoutConstraint:0x6080000ba9a0 UIView:0x7f816bc66320.height == 36>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2017-04-06 09:54:55.826896+0800 Demo[42206:1126591] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<MASLayoutConstraint:0x6000000babe0 UILabel:0x7f816bd2fb90.top == UITableViewCellContentView:0x7f816bd310a0.top + 8>",
    "<MASLayoutConstraint:0x6000000bafa0 UILabel:0x7f816bd34170.top == UILabel:0x7f816bd2fb90.bottom + 10>",
    "<MASLayoutConstraint:0x6000000bb2a0 UIView:0x7f816bd34400.top == UILabel:0x7f816bd34170.bottom + 10>",
    "<MASLayoutConstraint:0x6000000bb420 UIView:0x7f816bd34400.height == 36>",
    "<MASLayoutConstraint:0x6000000bb660 UIImageView:0x7f816bd329c0.top == UIView:0x7f816bd34400.bottom + 10>",
    "<MASLayoutConstraint:0x6000000bb720 UIImageView:0x7f816bd329c0.bottom == UITableViewCellContentView:0x7f816bd310a0.bottom - 10>",
    "<NSLayoutConstraint:0x6000000980b0 UITableViewCellContentView:0x7f816bd310a0.height == 71>"
)

Will attempt to recover by breaking constraint 
<MASLayoutConstraint:0x6000000bb420 UIView:0x7f816bd34400.height == 36>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.

**Comment by depaba** [comment]
你好，你可以给每个view设置一个mas_key,然后再把log发给我看，要不然这样子我很难看出什么问题。

**Comment by depaba** [comment]
我这个工程主要是为了实现sunnyxx的UIView-FDCollapsibleConstraints这个工程的代码版；
如果非到必要时刻，请不要使用；
我建议你最好使用Masonry的mas_updateConstraints这个来代替，一般情况下都是能实现你想要的功能的。
